# Data Understanding

The dataset used in this analysis is the US Accidents dataset, which contains detailed records of traffic accidents across the United States.

Each row represents a single accident, with information describing:

- Time and location of the accident
- Severity level of the accident
- Weather and environmental conditions
- Road infrastructure characteristics
- Visibility and atmospheric conditions

The dataset includes both numerical and categorical variables, making it suitable for exploratory data analysis and potential machine learning applications.

---

## Dataset Structure

The dataset contains 100,000 records and multiple features such as:

- Temporal features (Start_Time, End_Time)
- Geographic features (Start_Lat, Start_Lng, City, State)
- Weather conditions (Temperature, Humidity, Wind Speed, etc.)
- Road features (Junction, Traffic Signal, Crossing)
- Target variable: Severity

---

In [11]:
import pandas as pd

In [12]:
df = pd.read_csv("../data/raw/US_Accidents_March23.csv", nrows=100000)

In [13]:
df.shape

(100000, 46)

In [14]:
df.head(5)

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,Source2,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,Source2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,Source2,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,0.01,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,Source2,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,Source2,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,0.01,...,False,False,False,False,True,False,Day,Day,Day,Day

In [15]:
df.tail()

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
99995,A-100002,Source2,3,2016-04-05 15:52:14,2016-04-05 16:52:14,32.731979,-117.111244,NaN,NaN,0.0,...,False,False,False,False,False,False,Day,Day,Day,Day
99996,A-100003,Source2,3,2016-04-05 15:57:10,2016-04-05 16:57:10,33.913029,-118.125389,NaN,NaN,0.0,...,False,False,False,False,False,False,Day,Day,Day,Day
99997,A-100004,Source2,2,2016-04-05 16:02:16,2016-04-05 17:02:16,34.121517,-117.536896,NaN,NaN,0.0,...,False,False,False,False,True,False,Day,Day,Day,Day
99998,A-100005,Source3,2,2016-04-05 16:01:17,2016-04-05 17:01:17,33.995079,-117.361183,NaN,NaN,0.0,...,False,False,False,False,False,False,Day,Day,Day,Day
99999,A-100006,Source2,2,2016-04-05 16:06:41,2016-04-05 17:06:41,34.034119,-118.013443,NaN,NaN,0.0,...,False,False,False,False,False,False,Day,Day,Day,Day

In [16]:
df.columns.to_list()

['ID',
 'Source',
 'Severity',
 'Start_Time',
 'End_Time',
 'Start_Lat',
 'Start_Lng',
 'End_Lat',
 'End_Lng',
 'Distance(mi)',
 'Description',
 'Street',
 'City',
 'County',
 'State',
 'Zipcode',
 'Country',
 'Timezone',
 'Airport_Code',
 'Weather_Timestamp',
 'Temperature(F)',
 'Wind_Chill(F)',
 'Humidity(%)',
 'Pressure(in)',
 'Visibility(mi)',
 'Wind_Direction',
 'Wind_Speed(mph)',
 'Precipitation(in)',
 'Weather_Condition',
 'Amenity',
 'Bump',
 'Crossing',
 'Give_Way',
 'Junction',
 'No_Exit',
 'Railway',
 'Roundabout',
 'Station',
 'Stop',
 'Traffic_Calming',
 'Traffic_Signal',
 'Turning_Loop',
 'Sunrise_Sunset',
 'Civil_Twilight',
 'Nautical_Twilight',
 'Astronomical_Twilight']

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 46 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   ID                     100000 non-null  str
 1   Source                 100000 non-null  str
 2   Severity               100000 non-null  int64
 3   Start_Time             100000 non-null  str
 4   End_Time               100000 non-null  str
 5   Start_Lat              100000 non-null  float64
 6   Start_Lng              100000 non-null  float64
 7   End_Lat                0 non-null       float64
 8   End_Lng                0 non-null       float64
 9   Distance(mi)           100000 non-null  float64
 10  Description            100000 non-null  str
 11  Street                 100000 non-null  str
 12  City                   99999 non-null   str
 13  County                 100000 non-null  str
 14  State                  100000 non-null  str
 15  Zipcode                99993 non-null   str
 16  Country                100000 non-null  str
 17  Timezone               99993 non-null   str
 18  Airport_Code           99993 non-null   str
 19  Weather_Timestamp      98946 non-null   str
 20  Temperature(F)         98409 non-null   float64
 21  Wind_Chill(F)          4322 non-null    float64
 22  Humidity(%)            98144 non-null   float64
 23  Pressure(in)           98708 non-null   float64
 24  Visibility(mi)         98154 non-null   float64
 25  Wind_Direction         98936 non-null   str
 26  Wind_Speed(mph)        76180 non-null   float64
 27  Precipitation(in)      7368 non-null    float64
 28  Weather_Condition      98396 non-null   str
 29  Amenity                100000 non-null  bool
 30  Bump                   100000 non-null  bool
 31  Crossing               100000 non-null  bool
 32  Give_Way               100000 non-null  bool
 33  Junction               100000 non-null  bool
 34  No_Exit                100000 non-null  bool
 35  Railway                100000 non-null  bool
 36  Roundabout             100000 non-null  bool
 37  Station                100000 non-null  bool
 38  Stop                   100000 non-null  bool
 39  Traffic_Calming        100000 non-null  bool
 40  Traffic_Signal         100000 non-null  bool
 41  Turning_Loop           100000 non-null  bool
 42  Sunrise_Sunset         99999 non-null   str
 43  Civil_Twilight         99999 non-null   str
 44  Nautical_Twilight      99999 non-null   str
 45  Astronomical_Twilight  99999 non-null   str
dtypes: bool(13), float64(12), int64(1), str(20)
memory usage: 26.4 MB

In [18]:
df.isnull().sum()

ID                            0
Source                        0
Severity                      0
Start_Time                    0
End_Time                      0
Start_Lat                     0
Start_Lng                     0
End_Lat                  100000
End_Lng                  100000
Distance(mi)                  0
Description                   0
Street                        0
City                          1
County                        0
State                         0
Zipcode                       7
Country                       0
Timezone                      7
Airport_Code                  7
Weather_Timestamp          1054
Temperature(F)             1591
Wind_Chill(F)             95678
Humidity(%)                1856
Pressure(in)               1292
Visibility(mi)             1846
Wind_Direction             1064
Wind_Speed(mph)           23820
Precipitation(in)         92632
Weather_Condition          1604
Amenity                       0
Bump                          0
Crossing                      0
Give_Way                      0
Junction                      0
No_Exit                       0
Railway                       0
Roundabout                    0
Station                       0
Stop                          0
Traffic_Calming               0
Traffic_Signal                0
Turning_Loop                  0
Sunrise_Sunset                1
Civil_Twilight                1
Nautical_Twilight             1
Astronomical_Twilight         1
dtype: int64

In [19]:
df.describe()

,Severity,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Speed(mph),Precipitation(in)
count,100000.000000,100000.000000,100000.000000,0.0,0.0,100000.000000,98409.000000,4322.000000,98144.000000,98708.000000,98154.000000,76180.000000,7368.000000
mean,2.448120,35.630369,-119.322756,NaN,NaN,0.011345,66.641262,48.845812,59.794170,29.961021,9.338639,8.044165,0.025786
std,0.499931,2.101259,3.663525,NaN,NaN,0.262244,12.703846,19.898270,23.184442,0.275672,1.885828,4.298926,0.051695
min,1.000000,32.542587,-123.813927,NaN,NaN,0.000000,3.200000,-8.400000,4.000000,2.980000,0.100000,0.000000,0.000000
25%,2.000000,33.957775,-121.828468,NaN,NaN,0.000000,57.900000,37.100000,43.000000,29.890000,10.000000,4.600000,0.000000
50%,2.000000,34.168579,-118.384232,NaN,NaN,0.000000,66.000000,42.500000,62.000000,29.970000,10.000000,6.900000,0.000000
75%,3.000000,37.776682,-117.916023,NaN,NaN,0.010000,75.000000,63.000000,78.000000,30.060000,10.000000,10.400000,0.030000
max,4.000000,41.428753,-81.550728,NaN,NaN,51.130000,114.100000,107.000000,100.000000,33.040000,80.000000,241.700000,0.550000

In [20]:
df.duplicated().sum()

np.int64(0)